### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by ashiktantony** [JairoSalazarV/HypRaspCam#2]
Can you tell me how to uninstall the Hypraspcam pgm... Installation gone wrong I think

**Comment by JairoSalazarV** [comment]
I don't have an uninstall script.

The shortest path is reinstall raspbian. If it is not an option: you would
open the installation script with a text editor and revert the process
manually, I consider it is not a complex process.

Hopefully it helps.

Best,
Jairo Salazar

**Comment by Wa11facerr** [comment]
In your publication, you stated that it the client can run on android, how do i do that?

**Comment by JairoSalazarV** [comment]
> In your publication, you stated that it the client can run on android, how do i do that?

Due to it was developed on Qt, you could compile it as an android app. In the old versions of Qt, it was simple and straightforward, in recent versions, you may need to import the project and update some of its dependencies.

**Comment by Wa11facerr** [comment]
Thank you for answering my question, as i dont have time to update everything, and have spent the past 3 days doing so i am tired. 

The HypCam android apk. It doesnt run under latest version of android. 

Also, your squareHSI beta doesnt run under 64bit raspberry pi either. 

So im stuck asking you for help to update them because it will be very fast amd easy for you. 

I want to test out your device quickly and see which ways can improve the finish product. Ive been fighting with my raspberry pi dependencies the past 72hrs lol.
